config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'application#hello'
  #
  get 'books/:id/bookmarks' => 'books#bookmarks', :as => :book_bookmarks
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    # Just some idea to compare deltas between different points in time
    set_bookmark
    current_bookmarks = Bookmark.where(book_id: @bookmark.book_id)
    cur_index = current_bookmarks.index(@bookmark)
    prev_index = cur_index - 1
    prev_bookmark =  prev_index >= 0? current_bookmarks[prev_index] : @bookmark
    pages_read =  @bookmark.page - prev_bookmark.page

    @pages_read = pages_read
  end

  # GET /bookmarks/new
  def new
    puts params[:book_id]
    if params[:book_id]
      @bookmark = Bookmark.new(book_id: params[:post_id])
    else
      @bookmark = Bookmark.new
    end
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html {redirect_to @bookmark, notice: 'Bookmark was successfully created.'}
        format.json {render :show, status: :created, location: @bookmark}
      else
        format.html {render :new}
        format.json {render json: @bookmark.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html {redirect_to @bookmark, notice: 'Bookmark was successfully updated.'}
        format.json {render :show, status: :ok, location: @bookmark}
      else
        format.html {render :edit}
        format.json {render json: @bookmark.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html {redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def find_related_book(book_id)
    Book.find(book_id)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bookmark_params
    params.require(:bookmark).permit(:note, :book_id, :entry_date, :page, :progess)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    set_book
    @cur_bookmarks = @book.bookmarks
    pages_read = @cur_bookmarks.max_by {|m| m[:page]}.page
    progress = (pages_read.to_f / @book.total_page.to_f) * 100
    @progress_bar = progress
    date_array= @cur_bookmarks.pluck(:entry_date)
    page_array = @cur_bookmarks.pluck(:page)
    @progress_line = Hash[date_array.zip(page_array)]
    puts @progress_line
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html {redirect_to @book, notice: 'Book was successfully created.'}
        format.json {render :show, status: :created, location: @book}
      else
        format.html {render :new}
        format.json {render json: @book.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html {redirect_to @book, notice: 'Book was successfully updated.'}
        format.json {render :show, status: :ok, location: @book}
      else
        format.html {render :edit}
        format.json {render json: @book.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html {redirect_to books_url, notice: 'Book was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def bookmarks
    set_book
    @bookmarks = @book.bookmarks
    render "bookmarks/index"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def book_params
    params.require(:book).permit(:title, :author, :desc, :total_page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark, local: true) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :entry_date %>
    <%= form.date_select :entry_date %>
  </div>

  <div class="field">
    <%= form.label :page %>
    <%= form.number_field :page %>
  </div>

  <div class="field">
    <%= form.label :progess %>
    <%= form.number_field :progess %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <% if params[:book_id] %>
    <%= form.hidden_field :book_id, value: params[:book_id] %>
  <% else %>
    <div class="field">
      <%= form.label :book_id %>
      <%= form.number_field :book_id %>
    </div>
  <% end %>

<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Book</th>
      <th>Entry date</th>
      <th>Page</th>
      <th>Progess</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.note %></td>
        <td><%= bookmark.book_id %></td>
        <td><%= bookmark.entry_date %></td>
        <td><%= bookmark.page %></td>
        <td><%= bookmark.progess %></td>
        <td><%= link_to 'Show', bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @bookmark.note %>
</p>

<p>
  <strong>Book:</strong>
  <%= @bookmark.book_id %>
</p>

<p>
  <strong>Entry date:</strong>
  <%= @bookmark.entry_date %>
</p>

<p>
  <strong>Page:</strong>
  <%= @bookmark.page %>
</p>

<p>
  <strong>Progess:</strong>
  <%= @bookmark.progess %>
</p>

<p>
  <strong>Pages Read since:</strong>
  <%= @pages_read %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %> |
<%= link_to 'Back To The book', book_path(@bookmark.book)%>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>


  <div class="field">
    <%= form.label :total_page %>
    <%= form.text_field :total_page %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.desc %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

</table>
<h2><%= @jenny%> </h2>
<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Book Summary</h2>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @book.desc %>
</p>

<p>
  <strong>Total Pages:</strong>
  <%= @book.total_page %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %> |

<%= link_to "Add Bookmark", new_bookmark_path(book_id: @book.id) %>

<h2>Progress Update</h2>


<div class="container">
  <h3>Progress Chart</h3>
  <%= line_chart @progress_line, width: "800px", height: "500px", colors: ["#b00", "#666"]   %>


</div>

<div class="container">
  <h3>Most read days</h3>

  <%= bar_chart @progress_line , width: "800px", height: "500px" %>
</div>


<div class="container">
  <h3><%= @progress_bar %> % of the book complete
  </h3>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width:<%= @progress_bar%>%">
    </div>
  </div>
</div>

<h4> Current Bookmarks: </h4>
<% @book.bookmarks.each do |bookmark| %>
  <p>Some notes about this book mark: <%= bookmark.note %></p>
  <p>made on: <%= bookmark.entry_date %></p>
  <p>Current on: <%= bookmark.page %></p>
  <p>Current progress: <%= bookmark.progess %></p>
  <%= link_to 'See total progress', book_bookmarks_url(bookmark) %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= nav_bar fixed: :top, brand: "Book Marks" do %>
      <%= menu_group do %>
        <%= menu_item "All Books", books_path %>
      <%= menu_item "Existing bookmarks", bookmarks_path %>

      <%= menu_item "About Us", root_path %>
        <%= menu_item "Contact", root_path %>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>